=== nfwork/dbfound/src/main/resources/META-INF/conf.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" xmlns="http://dbfound.googlecode.com/conf"
	targetNamespace="http://dbfound.googlecode.com/conf">

	<xsd:element name="dbfound">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element maxOccurs="1" minOccurs="0" name="system"
					type="system_type" />
				<xsd:element maxOccurs="1" minOccurs="0" name="web"
					type="web_type" />
				<xsd:element maxOccurs="1" minOccurs="0" name="database"
					type="database_type" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="web_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="1" minOccurs="0" name="encoding" />
			<xsd:element maxOccurs="1" minOccurs="0" name="maxUploadSize" />
			<xsd:element maxOccurs="1" minOccurs="0" name="i18nProvide" />
			<xsd:element maxOccurs="1" minOccurs="0" name="mvcConfigFile" />
			<xsd:element maxOccurs="1" minOccurs="0" name="interceptor" />
			<xsd:element maxOccurs="1" minOccurs="0" name="exceptionHandler" />
			<xsd:element maxOccurs="1" minOccurs="0" name="listener" />
			<xsd:element maxOccurs="1" minOccurs="0" name="basePath" />
			<xsd:element maxOccurs="1" minOccurs="0" name="jsonStringAutoCover" />
			<xsd:element maxOccurs="1" minOccurs="0" name="openSession" />
			<xsd:element maxOccurs="1" minOccurs="0" name="apiAllowUrls" />
			<xsd:element maxOccurs="1" minOccurs="0" name="controllerPaths" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="system_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="1" minOccurs="0" name="openLog" />
			<xsd:element maxOccurs="1" minOccurs="0" name="logWithParamSql" />
			<xsd:element maxOccurs="1" minOccurs="0" name="underscoreToCamelCase" />
			<xsd:element maxOccurs="1" minOccurs="0" name="camelCaseToUnderscore" />
			<xsd:element maxOccurs="1" minOccurs="0" name="modeRootPath" />
			<xsd:element maxOccurs="1" minOccurs="0" name="modelModifyCheck" />
			<xsd:element maxOccurs="1" minOccurs="0" name="dateTimeFormat" />
			<xsd:element maxOccurs="1" minOccurs="0" name="dateFormat" />
			<xsd:element maxOccurs="1" minOccurs="0" name="sqlCompareIgnoreCase" />
			<xsd:element maxOccurs="1" minOccurs="0" name="openDSql" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="database_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="jdbcConnectionProvide">
				<xsd:complexType>
					<xsd:attribute name="provideName" />
					<xsd:attribute name="driverClass" />
					<xsd:attribute name="dialect" />
					<xsd:attribute name="url" />
					<xsd:attribute name="username" />
					<xsd:attribute name="password" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="dataSourceConnectionProvide">
				<xsd:complexType>
					<xsd:choice maxOccurs="unbounded" minOccurs="0">
						<xsd:element maxOccurs="unbounded" minOccurs="0"
							name="properties" type="properties_type" />
					</xsd:choice>
					<xsd:attribute name="provideName" />
					<xsd:attribute name="className" />
					<xsd:attribute name="dataSource" />
					<xsd:attribute name="dialect" />
				</xsd:complexType>
			</xsd:element>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="properties_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="property"
				type="property_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="property_type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
	</xsd:complexType>
</xsd:schema>

=== nfwork/dbfound/src/test/resources/dbfound-conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbfound xmlns="http://dbfound.googlecode.com/conf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dbfound.googlecode.com/conf https://raw.githubusercontent.com/nfwork/dbfound/master/tags/conf.xsd">

	<system>
		<openLog>true</openLog>
		<modeRootPath>${@classpath}/model</modeRootPath>
		<queryLimit>true</queryLimit>
		<queryLimitSize>5000</queryLimitSize>
		<reportQueryLimitSize>50000</reportQueryLimitSize>
	</system>

	<database>
		<dataSourceConnectionProvide className="org.apache.commons.dbcp.BasicDataSource" dialect="MySqlDialect">
			<properties>
				<property name="driverClassName" value="com.mysql.jdbc.Driver" />
				<property name="url" value="jdbc:mysql://127.0.0.1/dbfound?useUnicode=true&amp;characterEncoding=utf8" />
				<property name="username" value="dbfound" />
				<property name="password" value="dbfound" />
				<property name="initialSize" value="5" />
				<property name="maxActive" value="200" />
				<property name="maxIdle" value="5" />
				<property name="testOnBorrow" value="true" />
				<property name="validationQuery" value="select 1" />
			</properties>
		</dataSourceConnectionProvide>
	</database>

	<web>
		<encoding>utf-8</encoding>
		<interceptor>dbfount.test.core.AccessCheckInterceptor</interceptor>
		<maxUploadSize>20</maxUploadSize>
	</web>

</dbfound>
