=== nfwork/dbfound/src/main/resources/META-INF/model.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
			xmlns:d="http://dbfound.googlecode.com/model" targetNamespace="http://dbfound.googlecode.com/model">

	<xsd:element name="model">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="query" type="d:query_type">
					<xsd:unique name="queryParamUnique">
						<xsd:selector xpath="d:param"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
					<xsd:unique name="queryFilterUnique">
						<xsd:selector xpath="d:filter"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
				</xsd:element>
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute" type="d:execute_type">
					<xsd:unique name="executeParamUnique">
						<xsd:selector xpath="d:param"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="connectionProvide" />
		</xsd:complexType>
		<xsd:unique name="modelParamUnique">
			<xsd:selector xpath="d:param"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
		<xsd:unique name="modelQueryUnique">
			<xsd:selector xpath="d:query"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
		<xsd:unique name="modelExecuteUnique">
			<xsd:selector xpath="d:execute"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
	</xsd:element>

	<xsd:complexType name="query_type">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
			<xsd:element name="sql" type="d:sql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="filter" type="d:filter_type">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="verifier">
				<xsd:complexType>
					<xsd:attribute name="express" />
					<xsd:attribute name="message" />
					<xsd:attribute name="code" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="pagerSize" />
		<xsd:attribute name="exportSize" />
		<xsd:attribute name="maxPagerSize" />
		<xsd:attribute name="name" />
		<xsd:attribute name="queryTimeout" />
		<xsd:attribute name="adapter" />
		<xsd:attribute name="entity" />
		<xsd:attribute name="connectionProvide" />
		<xsd:attribute name="printContext" />
	</xsd:complexType>

	<xsd:complexType name="filter_type">
		<xsd:attribute name="active">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="condition" />
		<xsd:attribute name="express" />
		<xsd:attribute name="dataType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="varchar" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="date" />
					<xsd:enumeration value="boolean" />
					<xsd:enumeration value="collection" />
					<xsd:enumeration value="file" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="scope">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="value" />
		<xsd:attribute name="innerPath" />
	</xsd:complexType>

	<xsd:complexType name="execute_type">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
			<xsd:element minOccurs="0" name="sqls" type="d:sqls_type" />
		</xsd:sequence>
		<xsd:attribute name="name" />
		<xsd:attribute name="adapter" />
		<xsd:attribute name="connectionProvide" />
	</xsd:complexType>

	<xsd:complexType name="param_type">
		<xsd:attribute name="name" use="required" />
		<xsd:attribute name="dataType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="varchar" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="date" />
					<xsd:enumeration value="boolean" />
					<xsd:enumeration value="collection" />
					<xsd:enumeration value="file" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="scope">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoSession">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoCookie">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" />
		<xsd:attribute name="ioType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="out" />
					<xsd:enumeration value="in" />
					<xsd:enumeration value="both" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="UUID">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="batchAssign">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="emptyAsNull">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="fileNameParam" />
		<xsd:attribute name="innerPath" />
	</xsd:complexType>

	<xsd:complexType name="sql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="sqlTrim_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="sqlPart_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
		<xsd:attribute name="type">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="if" />
					<xsd:enumeration value="elseif" />
					<xsd:enumeration value="else" />
					<xsd:enumeration value="for" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoCompletion">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoClearComma">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="condition" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="separator" />
		<xsd:attribute name="begin" />
		<xsd:attribute name="end" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="sqls_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="requiredDataType">
						<xsd:simpleType>
							<xsd:restriction base="xsd:NMTOKEN">
								<xsd:enumeration value="list" />
								<xsd:enumeration value="map" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="caseSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="whenSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
		<xsd:attribute name="when" use="required" />
	</xsd:complexType>

	<xsd:complexType name="otherwiseSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="batchSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql"  type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
		<xsd:attribute name="cursor" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="cursorRootPath" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="executeSql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
		<xsd:attribute name="generatedKeyParam" />
		<xsd:attribute name="affectedCountParam" />
	</xsd:complexType>

	<xsd:complexType name="querySql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="setContextData_type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
		<xsd:attribute name="param" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="valueTemplate" />
		<xsd:attribute name="scope" >
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="inCurrentPath" >
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="batchExecuteSql_type" mixed="true">
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="affectedCountParam" />
		<xsd:attribute name="batchSize" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="java_type">
		<xsd:attribute name="className" />
		<xsd:attribute name="method" />
	</xsd:complexType>

	<xsd:complexType name="collisionSql_type">
		<xsd:attribute name="where" use="required" />
		<xsd:attribute name="message" />
		<xsd:attribute name="code" />
	</xsd:complexType>

</xsd:schema>

=== nfwork/dbfound/src/test/resources/model/gc/workRegist.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">

	<query>
		<param name="project_id" dataType="number" scope="param" />
		<param name="work_date" dataType="varchar" scope="param" />
		<sql>
		  <![CDATA[
			SELECT e.*,
			       ${@work_date} work_date,
			       ${@project_id} project_id,
			       (select CONCAT(CONCAT(project_code,'-'),project_name) from gc_project g where g.project_id = ${@project_id}) project_name
			 FROM gc_employee e
			 where not exists (
			   select 1 from gc_work_record r
			   where e.employee_id = r.employee_id
			    and r.project_id = ${@project_id}
			    and r.work_date = ${@work_date}
			 )
		   ]]>
		</sql>
	</query>
	
	<query name="displayQuery">
		<param name="project_id" dataType="number" scope="param" />
		<param name="employee_id" dataType="number" />
		<param name="date" dataType="varchar" scope="param" />
		<sql>
		  <![CDATA[
			   select * from gc_work_record r
			   where r.project_id = ${@project_id}
			    and r.employee_id = ${@employee_id}
			    and r.work_date like '#{@date}%'
		   ]]>
		</sql>
	</query>

	<query name="unRegist">
		<sql>
		  <![CDATA[
			SELECT r.*,
				   e.employee_code,
				   e.employee_name,
			       (select CONCAT(CONCAT(project_code,'-'),project_name) from gc_project g where g.project_id = r.project_id) project_name
			 FROM gc_work_record r,gc_employee e
			 where r.employee_id = e.employee_id
			  and IFNULL(r.settlement_flag,'N') != 'Y'
			 #AND_CLAUSE#
		   ]]>
		</sql>
		<filter name="project_id" express="project_id = ${@project_id} " />
		<filter name="work_date" express="r.work_date = ${@work_date} " />
	</query>

	<execute name="regiest">
		<param name="employee_id" dataType="number" />
		<param name="project_id" dataType="number" scope="param" />
		<param name="work_date" dataType="varchar" scope="param" />
		<sqls>
			<whenSql
				when="not exists (select 1 from gc_work_record 
		                                       where employee_id = ${@employee_id}
		                                        and project_id = ${@project_id}
		                                        and work_date = ${@work_date}
		                                       )">
				<executeSql>
				  <![CDATA[
					 insert into gc_work_record(employee_id,
												project_id,
												work_date
												)
										values(${@employee_id},
										         ${@project_id},
										         ${@work_date})
					]]>
				</executeSql>
			</whenSql>
		</sqls>
	</execute>

	<execute name="unAddRegiest">
		<param name="employee_id" dataType="number" />
		<param name="project_id" dataType="number" scope="param" />
		<param name="work_date" dataType="varchar" scope="param" />
		<param name="work_id" dataType="number" />
		<sqls>
		    <querySql>
		       <![CDATA[
				 select work_id from gc_work_record 
				  where employee_id = ${@employee_id}
				    and project_id = ${@project_id}
				    and work_date = ${@work_date}
				]]>
		    </querySql>
		    <collisionSql where="exists (select 1 from gc_work_record 
				  where work_id = ${@work_id}
				   and IFNULL(settlement_flag,'N') = 'Y')" message="已结算工时，不能取消！"/>
			<executeSql>
			  <![CDATA[
				 delete from gc_work_record 
				  where work_id = ${@work_id}
				]]>
			</executeSql>
		</sqls>
	</execute>
	
	<execute name="unRegiest">
		<param name="work_id" dataType="number" />
		<param name="employee_name" dataType="varchar" />
		<param name="work_date" dataType="varchar" />
		<sqls>
		    <collisionSql where="exists (select 1 from gc_work_record 
				  where work_id = ${@work_id}
				   and IFNULL(settlement_flag,'N') = 'Y')" message="员工#{@employee_name}在#{@work_date}的报公已经结算，不能取消！"/>
			<executeSql>
			  <![CDATA[
				 delete from gc_work_record 
				  where work_id = ${@work_id}
				]]>
			</executeSql>
		</sqls>
	</execute>
</model>

=== nfwork/dbfound/WebRoot/WEB-INF/model/sys/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">
	
	<query pagerSize="10" >
		<sql>
		 <![CDATA[
			SELECT
				u.user_id,
				u.user_name,
				u.role_id,
				u.user_code,
				u.status,
				DATE_FORMAT(u.create_date,'%Y-%m-%d') create_date,
				DATE_FORMAT(u.last_update_date,'%Y-%m-%d') last_update_date,
				(select CONCAT(CONCAT(user_code,'-'),user_name) from sys_user where user_id =u.last_update_by) last_update_user,
				u.create_date date,
				u.password
			FROM SYS_USER u
			#WHERE_CLAUSE#
			order by u.user_code
		 ]]>
		</sql>
		<filter name="timefrom" express="create_date &gt;= ${@timefrom}" />
		<filter name="timeto" express="create_date &lt;= ${@timeto}" />
		<filter name="user_code" express="user_code like '#{@user_code}'" />
		<filter name="user_name" express="user_name like ${@user_name}" />
		<filter name="role_id" express="role_id = ${@role_id}" />
		<filter name="status_code" express="status = ${@status_code}" />
	</query>
	
	<query name="combo" pagerSize="50" >
		<sql>
		 <![CDATA[
			SELECT
				u.user_id,
				u.user_name,
				u.user_code
			FROM SYS_USER u
			order by u.user_code
		 ]]>
		</sql>
	</query>

	<execute name="add">
		<param name="user_code" dataType="varchar" />
		<param name="user_name" dataType="varchar" />
		<param name="password" dataType="varchar"/>
		<param name="status" dataType="varchar" />
		<param name="role_id" dataType="number" />
		<param name="user_id" dataType="number" scope="session" />
		<sqls>
			<collisionSql
				where="exists (select 1 from sys_user where user_code= ${@user_code})"
				message="用户编号:#{@user_code} 已经使用！" />
			<executeSql>
			 <![CDATA[
			    INSERT INTO sys_user
				   (user_code,
					user_name,
					password,
					role_id,
					status,
					create_by,
					create_date,
					last_update_by,
					last_update_date)
				VALUES
					(${@user_code},
					${@user_name},
					${@password},
					${@role_id},
					${@status},
					${@user_id},
					NOW(),
					${@user_id},
					NOW())
			 ]]>
			</executeSql>
		</sqls>
	</execute>

	<execute name="update">
		<param name="user_name" dataType="varchar" />
		<param name="role_id" dataType="number" />
		<param name="password" dataType="varchar" />
		<param name="status" dataType="varchar" />
		<param name="user_id" dataType="number" scope="session" />
		<param name="uid" sourcePath="user_id" dataType="number" />
		<sqls>
			<executeSql>
			  <![CDATA[
				update sys_user set 
					user_name = ${@user_name} ,
					role_id =${@role_id},
					password = ${@password} ,
					status =${@status},
					last_update_by = ${@user_id} ,
					last_update_date = NOW() 
				where user_id = ${@uid} 
			  ]]>
			</executeSql>
		</sqls>
	</execute>

	<execute name="delete">
		<param name="user_id" dataType="number" />
		<sqls>
			<executeSql>
			  <![CDATA[
				delete from sys_user where user_id= ${@user_id} 
			  ]]>
			</executeSql>
		</sqls>
	</execute>
</model>
