=== nfwork/dbfound/src/main/resources/META-INF/model.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
			xmlns:d="http://dbfound.googlecode.com/model" targetNamespace="http://dbfound.googlecode.com/model">

	<xsd:element name="model">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="query" type="d:query_type">
					<xsd:unique name="queryParamUnique">
						<xsd:selector xpath="d:param"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
					<xsd:unique name="queryFilterUnique">
						<xsd:selector xpath="d:filter"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
				</xsd:element>
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute" type="d:execute_type">
					<xsd:unique name="executeParamUnique">
						<xsd:selector xpath="d:param"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="connectionProvide" />
		</xsd:complexType>
		<xsd:unique name="modelParamUnique">
			<xsd:selector xpath="d:param"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
		<xsd:unique name="modelQueryUnique">
			<xsd:selector xpath="d:query"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
		<xsd:unique name="modelExecuteUnique">
			<xsd:selector xpath="d:execute"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
	</xsd:element>

	<xsd:complexType name="query_type">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
			<xsd:element name="sql" type="d:sql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="filter" type="d:filter_type">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="verifier">
				<xsd:complexType>
					<xsd:attribute name="express" />
					<xsd:attribute name="message" />
					<xsd:attribute name="code" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="pagerSize" />
		<xsd:attribute name="exportSize" />
		<xsd:attribute name="maxPagerSize" />
		<xsd:attribute name="name" />
		<xsd:attribute name="queryTimeout" />
		<xsd:attribute name="adapter" />
		<xsd:attribute name="entity" />
		<xsd:attribute name="connectionProvide" />
		<xsd:attribute name="printContext" />
	</xsd:complexType>

	<xsd:complexType name="filter_type">
		<xsd:attribute name="active">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="condition" />
		<xsd:attribute name="express" />
		<xsd:attribute name="dataType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="varchar" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="date" />
					<xsd:enumeration value="boolean" />
					<xsd:enumeration value="collection" />
					<xsd:enumeration value="file" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="scope">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="value" />
		<xsd:attribute name="innerPath" />
	</xsd:complexType>

	<xsd:complexType name="execute_type">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
			<xsd:element minOccurs="0" name="sqls" type="d:sqls_type" />
		</xsd:sequence>
		<xsd:attribute name="name" />
		<xsd:attribute name="adapter" />
		<xsd:attribute name="connectionProvide" />
	</xsd:complexType>

	<xsd:complexType name="param_type">
		<xsd:attribute name="name" use="required" />
		<xsd:attribute name="dataType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="varchar" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="date" />
					<xsd:enumeration value="boolean" />
					<xsd:enumeration value="collection" />
					<xsd:enumeration value="file" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="scope">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoSession">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoCookie">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" />
		<xsd:attribute name="ioType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="out" />
					<xsd:enumeration value="in" />
					<xsd:enumeration value="both" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="UUID">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="batchAssign">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="emptyAsNull">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="fileNameParam" />
		<xsd:attribute name="innerPath" />
	</xsd:complexType>

	<xsd:complexType name="sql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="sqlTrim_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="sqlPart_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
		<xsd:attribute name="type">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="if" />
					<xsd:enumeration value="elseif" />
					<xsd:enumeration value="else" />
					<xsd:enumeration value="for" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoCompletion">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoClearComma">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="condition" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="separator" />
		<xsd:attribute name="begin" />
		<xsd:attribute name="end" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="sqls_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="requiredDataType">
						<xsd:simpleType>
							<xsd:restriction base="xsd:NMTOKEN">
								<xsd:enumeration value="list" />
								<xsd:enumeration value="map" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="caseSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="whenSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
		<xsd:attribute name="when" use="required" />
	</xsd:complexType>

	<xsd:complexType name="otherwiseSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="batchSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql"  type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
		<xsd:attribute name="cursor" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="cursorRootPath" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="executeSql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
		<xsd:attribute name="generatedKeyParam" />
		<xsd:attribute name="affectedCountParam" />
	</xsd:complexType>

	<xsd:complexType name="querySql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="setContextData_type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
		<xsd:attribute name="param" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="valueTemplate" />
		<xsd:attribute name="scope" >
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="inCurrentPath" >
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="batchExecuteSql_type" mixed="true">
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="affectedCountParam" />
		<xsd:attribute name="batchSize" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="java_type">
		<xsd:attribute name="className" />
		<xsd:attribute name="method" />
	</xsd:complexType>

	<xsd:complexType name="collisionSql_type">
		<xsd:attribute name="where" use="required" />
		<xsd:attribute name="message" />
		<xsd:attribute name="code" />
	</xsd:complexType>

</xsd:schema>

=== nfwork/dbfound/src/test/resources/model/fnd/teacher.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">
	<query pagerSize="10">
		<sql>
		  <![CDATA[
			SELECT
			    t.teacher_id,
				t.teacher_code,
				t.teacher_name,
				t.email,
				t.enable_flag,
				t.telphone_num,
				t.last_update_by,
				DATE_FORMAT(t.create_date,'%Y-%m-%d') create_date,
				DATE_FORMAT(t.last_update_date,'%Y-%m-%d') last_update_date,
			    (select CONCAT(CONCAT(user_code,'-'),user_name) from sys_user where user_id =t.last_update_by) last_update_user
			FROM fnd_teacher t
			#WHERE_CLAUSE#
			order by t.teacher_code
		   ]]>
		</sql>
		<filter name="timefrom" express="create_date &gt;= ${@timefrom}  " />
		<filter name="timeto" express="create_date &lt;= ${@timeto} " />
		<filter name="status_code" express="enable_flag = ${@status_code} " />
		<filter name="teacher_code" express="teacher_code like ${@teacher_code} " />
		<filter name="teacher_name" express="teacher_name like ${@teacher_name} " />
	</query>

	<execute name="add">
		<param name="teacher_code" dataType="varchar" />
		<param name="teacher_name" dataType="varchar" />
		<param name="email" dataType="varchar" />
		<param name="enable_flag" dataType="varchar" />
		<param name="telphone_num" dataType="varchar" />
		<param name="role_id" dataType="number" ioType="out" />
		<param name="user_id" dataType="number" scope="session" />
		<sqls>
			<collisionSql
				where="exists (select 1 from fnd_teacher where teacher_code= ${@teacher_code})"
				message="编号:#{@teacher_code} 已经使用！" />
			<executeSql>
			   <![CDATA[
				INSERT INTO fnd_teacher
					(teacher_code,
					teacher_name,
					email,
					telphone_num,
					enable_flag,
					create_by,
					last_update_by,
					create_date,
					last_update_date)
				VALUES (${@teacher_code},
					${@teacher_name},
					${@email},
					${@telphone_num},
					${@enable_flag},
					${@user_id},
					${@user_id},
					NOW(),
					NOW())
				 ]]>
			</executeSql>
			<whenSql when="not exists (select 1 from sys_user where user_code= ${@teacher_code})" >
			    <querySql>
				   <![CDATA[
					 SELECT
					    r.role_id
					 FROM sys_role r
					 where role_code = 'TEACHER'
					 ]]>
				</querySql>
				<executeSql>
				   <![CDATA[
					 INSERT INTO sys_user
					   (user_code,
						user_name,
						password,
						role_id,
						status,
						create_by,
						create_date,
						last_update_by,
						last_update_date)
					VALUES
						(${@teacher_code},
						${@teacher_name},
						'123456',
						${@role_id},
						${@enable_flag},
						${@user_id},
						NOW(),
						${@user_id},
						NOW())
					 ]]>
				</executeSql>
			</whenSql>
		</sqls>
	</execute>

	<execute name="update">
		<param name="teacher_id" dataType="number" />
		<param name="teacher_code" dataType="varchar" />
		<param name="teacher_name" dataType="varchar" />
		<param name="enable_flag" dataType="varchar" />
		<param name="email" dataType="varchar" />
		<param name="telphone_num" dataType="varchar" />
		<param name="user_id" dataType="number" scope="session" />
		<sqls>
			<executeSql>
			  <![CDATA[
				update fnd_teacher set
					teacher_name = ${@teacher_name} ,
					email        = ${@email} ,
					enable_flag  = ${@enable_flag},
					telphone_num = ${@telphone_num} ,
					last_update_by =${@user_id} ,
					last_update_date = NOW()
				where teacher_id = ${@teacher_id}
				]]>
			</executeSql>
			<executeSql>
			  <![CDATA[
				update sys_user set
					status  = ${@enable_flag},
					last_update_by =${@user_id} ,
					last_update_date = NOW()
				where user_code = ${@teacher_code}
				  and status != ${@enable_flag}
				]]>
			</executeSql>
		</sqls>
	</execute>

	<query name="combo">
		<sql>
		  <![CDATA[
			SELECT
				t.teacher_id ,
				concat(concat(teacher_code,'-'),teacher_name) teacher_name
			FROM fnd_teacher t
			order by teacher_code
		  ]]>
		</sql>
	</query>
</model>

=== nfwork/dbfound/src/test/resources/model/sys/log.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">
	<execute name="openLog">
		<param name="message" value="开启日志成功！" ioType="out" />
		<sqls>
			<java className="com.nfwork.dbfound.util.LogUtil" method="openLog" />
		</sqls>
	</execute>

	<execute name="closeLog">
		<param name="message" value="关闭日志成功！" ioType="out" />
		<sqls>
			<java className="com.nfwork.dbfound.util.LogUtil" method="closeLog" />
		</sqls>
	</execute>
</model>

=== nfwork/dbfound/src/test/resources/model/gc/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">
	<query>
		<sql>
		  <![CDATA[
			SELECT * FROM gc_employee
			#WHERE_CLAUSE#
			order by employee_code
		   ]]>
		</sql>
		<filter name="employee_code" express="employee_code like ${@employee_code} " />
		<filter name="employee_name" express="employee_name like ${@employee_name} " />
	</query>
	
	<query name="combo">
		<sql>
		  <![CDATA[
			SELECT e.employee_id,
			       concat(concat(employee_code,'-'),employee_name) employee_name
            FROM gc_employee e
			order by employee_code
		   ]]>
		</sql>
	</query>

	<execute name="add">
		<param name="employee_code" dataType="varchar" />
		<param name="employee_name" dataType="varchar" />
		<sqls>
			<collisionSql
				where="exists (select 1 from gc_employee where employee_code= ${@employee_code})"
				message="工人编号:#{@employee_code} 已经使用！" />
			<executeSql>
			   <![CDATA[
				INSERT INTO gc_employee
					(employee_code,
					 employee_name
					)
				VALUES (${@employee_code},
					${@employee_name}
					)
				 ]]>
			</executeSql>
		</sqls>
	</execute>

	<execute name="update">
		<param name="employee_id" dataType="number" />
		<param name="employee_name" dataType="varchar" />
		<param name="price" dataType="number" />
		<sqls>
			<executeSql>
			  <![CDATA[
				update gc_employee set
					employee_name = ${@employee_name}
				where employee_id = ${@employee_id}
				]]>
			</executeSql>
		</sqls>
	</execute>

</model>

=== nfwork/dbfound/src/test/resources/model/job/jobQuery.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">
	<query name="teacher_query">
	    <param name="user_code" dataType="varchar" scope="session" />
		<sql>
		  <![CDATA[
			SELECT
			    teacher_name,
			    teacher_id
			FROM fnd_teacher t
			where t.teacher_code = ${@user_code}
		   ]]>
		</sql>
	</query>
	
	<query>
	    <param name="line_id" dataType="varchar" />
		<sql>
		  <![CDATA[
			SELECT l.line_id,
			       l.description,
			       l.score,
			       l.teacher_comment,
			       l.grade,
			       (select count(1) from sys_upload_file f where f.table_name ='job_lines' and pk_value = line_id) att_num,
			       (select c.code_name from sys_code c where c.code='JOB_LINE_STATUS'  and c.code_value= l.status ) status
			FROM job_lines l
			WHERE l.line_id = ${@line_id}
		   ]]>
		</sql>
	</query>
	
	<query pagerSize="10" name="header_query" >
	    <param name="user_code" dataType="varchar" scope="session" />
		<sql>
		  <![CDATA[
			SELECT
			    title,
				class_id,
				header_id,
				(select c.class_name from fnd_class c where c.class_id = t.class_id) class_name,
			    course_id,
			    status status_code,
			    (select  concat(concat(b.branch_code,'-'),b.branch_name) from fnd_branch b,fnd_course c where b.branch_id = c.branch_id and c.course_id= t.course_id) course_name,
				(SELECT  code_name  FROM sys_code t where t.code='JOB_STATUS'  and t.code_value= status) status_name,
				end_time,
				(select teacher_name from fnd_teacher te where te.teacher_id = t.teacher_id) teacher_name,
				(select count(1) from sys_upload_file f where f.table_name ='job_headers' and pk_value = header_id) att_num,
				t.last_update_by,
				DATE_FORMAT(t.create_date,'%Y-%m-%d') create_date,
				DATE_FORMAT(t.last_update_date,'%Y-%m-%d') last_update_date,
			    (select CONCAT(CONCAT(user_code,'-'),user_name) from sys_user where user_id =t.last_update_by) last_update_user
			FROM job_headers t
			where t.teacher_id = (SELECT teacher_id FROM fnd_teacher s WHERE s.teacher_code = ${@user_code})
			 #AND_CLAUSE#
			order by t.create_date desc
		   ]]>
		</sql>
		<filter name="timefrom" express="create_date &gt;= ${@timefrom}  " />
		<filter name="timeto" express="create_date &lt;= ${@timeto} " />
		<filter name="class_id" express="class_id = ${@class_id} " />
		<filter name="course_id" express="course_id = ${@course_id} " />
		<filter name="status_code" express="status = ${@status_code} " />
		<filter name="title" express="title like ${@title} " />
	</query>
</model>
