=== nfwork/dbfound/src/main/resources/META-INF/model.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
			xmlns:d="http://dbfound.googlecode.com/model" targetNamespace="http://dbfound.googlecode.com/model">

	<xsd:element name="model">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="query" type="d:query_type">
					<xsd:unique name="queryParamUnique">
						<xsd:selector xpath="d:param"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
					<xsd:unique name="queryFilterUnique">
						<xsd:selector xpath="d:filter"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
				</xsd:element>
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute" type="d:execute_type">
					<xsd:unique name="executeParamUnique">
						<xsd:selector xpath="d:param"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="connectionProvide" />
		</xsd:complexType>
		<xsd:unique name="modelParamUnique">
			<xsd:selector xpath="d:param"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
		<xsd:unique name="modelQueryUnique">
			<xsd:selector xpath="d:query"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
		<xsd:unique name="modelExecuteUnique">
			<xsd:selector xpath="d:execute"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
	</xsd:element>

	<xsd:complexType name="query_type">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
			<xsd:element name="sql" type="d:sql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="filter" type="d:filter_type">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="verifier">
				<xsd:complexType>
					<xsd:attribute name="express" />
					<xsd:attribute name="message" />
					<xsd:attribute name="code" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="pagerSize" />
		<xsd:attribute name="exportSize" />
		<xsd:attribute name="maxPagerSize" />
		<xsd:attribute name="name" />
		<xsd:attribute name="queryTimeout" />
		<xsd:attribute name="adapter" />
		<xsd:attribute name="entity" />
		<xsd:attribute name="connectionProvide" />
		<xsd:attribute name="printContext" />
	</xsd:complexType>

	<xsd:complexType name="filter_type">
		<xsd:attribute name="active">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="condition" />
		<xsd:attribute name="express" />
		<xsd:attribute name="dataType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="varchar" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="date" />
					<xsd:enumeration value="boolean" />
					<xsd:enumeration value="collection" />
					<xsd:enumeration value="file" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="scope">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="value" />
		<xsd:attribute name="innerPath" />
	</xsd:complexType>

	<xsd:complexType name="execute_type">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
			<xsd:element minOccurs="0" name="sqls" type="d:sqls_type" />
		</xsd:sequence>
		<xsd:attribute name="name" />
		<xsd:attribute name="adapter" />
		<xsd:attribute name="connectionProvide" />
	</xsd:complexType>

	<xsd:complexType name="param_type">
		<xsd:attribute name="name" use="required" />
		<xsd:attribute name="dataType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="varchar" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="date" />
					<xsd:enumeration value="boolean" />
					<xsd:enumeration value="collection" />
					<xsd:enumeration value="file" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="scope">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoSession">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoCookie">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" />
		<xsd:attribute name="ioType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="out" />
					<xsd:enumeration value="in" />
					<xsd:enumeration value="both" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="UUID">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="batchAssign">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="emptyAsNull">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="fileNameParam" />
		<xsd:attribute name="innerPath" />
	</xsd:complexType>

	<xsd:complexType name="sql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="sqlTrim_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="sqlPart_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
		<xsd:attribute name="type">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="if" />
					<xsd:enumeration value="elseif" />
					<xsd:enumeration value="else" />
					<xsd:enumeration value="for" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoCompletion">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoClearComma">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="condition" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="separator" />
		<xsd:attribute name="begin" />
		<xsd:attribute name="end" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="sqls_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="requiredDataType">
						<xsd:simpleType>
							<xsd:restriction base="xsd:NMTOKEN">
								<xsd:enumeration value="list" />
								<xsd:enumeration value="map" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="caseSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="whenSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
		<xsd:attribute name="when" use="required" />
	</xsd:complexType>

	<xsd:complexType name="otherwiseSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="batchSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql"  type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
		<xsd:attribute name="cursor" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="cursorRootPath" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="executeSql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
		<xsd:attribute name="generatedKeyParam" />
		<xsd:attribute name="affectedCountParam" />
	</xsd:complexType>

	<xsd:complexType name="querySql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="setContextData_type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
		<xsd:attribute name="param" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="valueTemplate" />
		<xsd:attribute name="scope" >
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="inCurrentPath" >
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="batchExecuteSql_type" mixed="true">
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="affectedCountParam" />
		<xsd:attribute name="batchSize" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="java_type">
		<xsd:attribute name="className" />
		<xsd:attribute name="method" />
	</xsd:complexType>

	<xsd:complexType name="collisionSql_type">
		<xsd:attribute name="where" use="required" />
		<xsd:attribute name="message" />
		<xsd:attribute name="code" />
	</xsd:complexType>

</xsd:schema>

=== nfwork/dbfound/src/test/resources/model/test/execute.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">

    <execute>
        <param name="role_id" dataType="number" ioType="out" />
        <param name="user_id" dataType="varchar" ioType="out" />
        <param name="user_name" dataType="varchar" ioType="out" />
        <param name="fields_size" dataType="number" sourcePath="fields.size" value="0" />
		<sqls>
			<collisionSql where="${@role} is null" message="role不能为空" code="10010" />
            <querySql>
				select ${@role} as role_id
			</querySql>
            <whenSql when="${@fields_size} > 0">
                <querySql>
                    select
                    <sqlPart type="for" sourcePath="fields">
                        ${@value} as #{@code}
                    </sqlPart>
                </querySql>
                <executeSql>
                    select
                    <sqlPart type="for" sourcePath="fields">
                        ${@value} as #{@code}
                    </sqlPart>
                </executeSql>
			</whenSql>
		</sqls>
	</execute>

    <execute name="ifPart">
        <param name="user_id" dataType="varchar" ioType="both" />
        <param name="user_name" dataType="varchar" ioType="both" />
		<sqls>
            <querySql>
                select
                <sqlTrim>
                    <sqlPart type="if" sourcePath="user_id">
                        1 as user_id,
                    </sqlPart>
                    <sqlPart type="if" sourcePath="user_name">
                        'lily' as user_name,
                    </sqlPart>
                    <sqlPart type="if" condition="${@user_code} is not null">
                        '10010' as user_code,
                    </sqlPart>
                </sqlTrim>
            </querySql>
			<executeSql>
                select
                <sqlTrim>
                    <sqlPart type="if" sourcePath="user_id">
                        1 as user_id,
                    </sqlPart>
                    <sqlPart type="if" sourcePath="user_name">
                        'lily' as user_name,
                    </sqlPart>
                    <sqlPart type="if" condition="${@user_code} is not null">
                        '10010' as user_code,
                    </sqlPart>
			    </sqlTrim>
			</executeSql>
            <executeSql>
                select
                    <sqlPart type="if" sourcePath="user_id" autoClearComma="true">
                        1 as user_id,
                    </sqlPart>
                    <sqlPart type="if" sourcePath="user_name" autoClearComma="true">
                        'lily' as user_name,
                    </sqlPart>
                    <sqlPart type="if" condition="${@user_code} is not null" autoClearComma="true">
                        '10010' as user_code,
                    </sqlPart>
            </executeSql>
		</sqls>
	</execute>

    <execute name="batchSql">
        <param name="user_id_0" ioType="out" scope="outParam" />
        <param name="user_id_1" ioType="out" scope="outParam" />
		<sqls>
			<batchSql sourcePath="users" item="user_id" index="index">
				<querySql>
					select ${@user_id} as user_id_#{@index}
				</querySql>
			</batchSql>
		</sqls>
	</execute>

    <execute name="batchExecuteSql">
        <sqls>
            <batchExecuteSql sourcePath="users" item="user_id" index="index">
                select
                    #BATCH_TEMPLATE_BEGIN#
                    ${@user_id} as user_id_#{@index}
                    #BATCH_TEMPLATE_END#
			</batchExecuteSql>
        </sqls>
    </execute>

    <execute name="adapter" adapter="dbfound.test.adapter.ExecuteTestAdapter">
        <sqls>
            <querySql>
				select 1 as user_id
			</querySql>
        </sqls>
    </execute>

</model>

=== nfwork/dbfound/WebRoot/WEB-INF/model/manager/fileManager.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dbfound.googlecode.com/model http://dbfound.googlecode.com/svn/tags/v2/model.xsd">

	<execute name="upload">
		<param name="path" dataType="varchar" />
		<param name="file_name" dataType="varchar" />
		<param name="file" dataType="file" />
		<sqls>
			<java className="com.nfwork.test.FileManager"/>
		</sqls>
	</execute>
	
	<execute name="listFile">
		<param name="path" dataType="varchar" />
		<sqls>
			<java className="com.nfwork.test.FileManager" method="listFile"/>
		</sqls>
	</execute>
	
	<execute name="delete">
		<param name="path" dataType="varchar" scope="param" />
		<param name="file_name" dataType="varchar" />
		<sqls>
			<java className="com.nfwork.test.FileManager" method="delete"/>
		</sqls>
	</execute>
	
	<execute name="down">
		<param name="path" dataType="varchar" sourcePath="param.parameters.path" />
		<param name="file_name" dataType="varchar" scope="param" />
		<param name="file" dataType="file" fileSaveType="disk" ioType="out"/>
		<sqls>
			<java className="com.nfwork.test.FileManager" method="down"/>
		</sqls>
	</execute>

</model>

=== nfwork/dbfound/src/test/resources/model/test/query.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">

    <query>
        <param name="fields_size" sourcePath="fields.size" value="0" dataType="number" />
        <sql>
            select
                <sqlPart condition="${@fields_size} = 0">
					*
				</sqlPart>
                <sqlPart type="if" sourcePath="fields">
					#{@fields}
				</sqlPart>
            from
             (
                  select 1 as user_id, 'lily' as user_name, '10000' as user_code
                  union
                  select 2 as user_id, 'lucy' as user_name, '10001' as user_code
              ) t
            #WHERE_CLAUSE#
            <sqlPart type="for" sourcePath="order_fields" item="field" begin="order by ">
                #{@field}
            </sqlPart>
        </sql>
        <filter name="ids" dataType="collection" express="user_id in (${@ids})" />
        <filter name="user_id" dataType="number" express="user_id = ${@user_id}" />
        <filter name="user_name" dataType="varchar" express="user_name = ${@user_name}" />
    </query>
</model>

=== nfwork/dbfound/src/test/resources/model/fnd/course.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">

	<query name="add_combo">
		<param name="user_code" dataType="varchar" scope="session" />
		<param name="class_id" dataType="number" />
		<sql>
		  <![CDATA[
			SELECT distinct
			  concat(concat(b.branch_code,'-'),b.branch_name) course_name,
			  t.course_id
			FROM fnd_course t,fnd_branch b
			WHERE t.branch_id = b.branch_id 
			AND t.enable_flag = 'Y'
			AND t.teacher_id = (SELECT te.teacher_id FROM fnd_teacher te WHERE te.teacher_code = ${@user_code} )
			and t.class_id =${@class_id}
			ORDER BY b.branch_code
		  ]]>
		</sql>
	</query>

	<query name="combo">
		<param name="user_code" dataType="varchar" scope="session" />
		<sql>
		  <![CDATA[
			SELECT distinct
			  concat(concat(b.branch_code,'-'),b.branch_name) course_name,
			  t.course_id
			FROM fnd_course t,fnd_branch b
			WHERE t.branch_id = b.branch_id 
			AND t.enable_flag = 'Y'
			AND t.teacher_id = (SELECT te.teacher_id FROM fnd_teacher te WHERE te.teacher_code = ${@user_code} )
			ORDER BY b.branch_code
		  ]]>
		</sql>
	</query>

	<query name="student_combo">
		<param name="user_code" dataType="varchar" scope="session" />
		<sql>
		  <![CDATA[
			SELECT
			  concat(concat(b.branch_code,'-'),b.branch_name) course_name,
			  t.course_id
			FROM fnd_course t,fnd_branch b
			WHERE t.branch_id = b.branch_id 
			AND t.enable_flag = 'Y'
			AND t.class_id = (SELECT c.class_id FROM fnd_class c,fnd_student s WHERE c.class_id= s.class_id and s.student_code = ${@user_code} )
			ORDER BY b.branch_code
		  ]]>
		</sql>
	</query>
</model>

=== nfwork/dbfound/src/test/resources/model/gc/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">
	<query pagerSize="10">
		<sql>
		  <![CDATA[
			SELECT * FROM gc_project
			#WHERE_CLAUSE#
		   ]]>
		</sql>
		<filter name="project_code" express="project_code like ${@project_code} " />
		<filter name="project_name" express="project_name like ${@project_name} " />
	</query>

	<execute name="add">
		<param name="project_code" dataType="varchar" />
		<param name="project_name" dataType="varchar" />
		<param name="price" dataType="number" />
		<sqls>
			<collisionSql
				where="exists (select 1 from gc_project where project_code= ${@project_code})"
				message="工程编号:#{@project_code} 已经使用！" />
			<executeSql>
			   <![CDATA[
				INSERT INTO gc_project
					(project_code,
					 project_name,
					 price
					)
				VALUES (${@project_code},
					${@project_name},
					${@price})
				 ]]>
			</executeSql>
		</sqls>
	</execute>

	<execute name="update">
		<param name="project_id" dataType="number" />
		<param name="project_name" dataType="varchar" />
		<param name="price" dataType="number" />
		<sqls>
			<executeSql>
			  <![CDATA[
				update gc_project set
					project_name = ${@project_name} ,
					price = ${@price} 
				where project_id = ${@project_id}
				]]>
			</executeSql>
		</sqls>
	</execute>

	<query name="combo">
		<sql>
		  <![CDATA[
			SELECT
				r.project_id ,
				CONCAT(CONCAT(project_code,'-'),project_name) project_name
			FROM gc_project r
			order by project_code
		  ]]>
		</sql>
	</query>
</model>
